---
title: "01-B-BHM-Simstudy-ORR"
author: "Sandro Gsteiger"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  word_document:
    fig_caption: yes
    fig_height: 4
    fig_width: 7
    highlight: 'default'
    reference_docx: word_template.docx
    toc: yes
    toc_depth: 4
  # html_document:
  #   toc: true
  #   toc_float: true
  #   number_sections: true
  # editor_options: 
  #   chunk_output_type: console
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_dir = "outputs")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

rm(list = ls())

for(s in dir("R")){
  source(file.path(".", "R", s))
}

r_seed <- 8945334
```

# Description
Simulation study to assess the predictive uncertainty in a binary endpoint analyzed with a Bayesian hierarchical model as a function of number of groups and sample size per group.

# Simulation setup and scenarios 

**Global parameters**
```{r}
sim.pars <- list(
  p.pop = 0.5,
  re.sd = 
)
```




# Simulation results
```{r}
sim <- simstd_bin(par.sim = list(p.pop = 0.5, re.sd = 0.2, n.studies = 5, n.sizes = c(20, 5, 5, 5, 5)), 
                  par.an = list(n_chains = 3, n_iter = 1500, n_burnin = 200, n_thin = 1,
                                monitor = c("p.new", "re.sd"),
                                model.file = "models/bin_abs_re_hn.jgmod",
                                prior = list(prior.fe.mean = boot::logit(0.3),
                                             prior.fe.prec = 1/10,
                                             prior.re.mean = 0,
                                             prior.re.prec = 1)
                  ), 
                  r.seed = NULL)
```








# Session info
```{r}
getwd()
sessionInfo()
```
